# twitter/util sbt build/test with coverage
name: sbt-build

env:
  JAVA_OPTS: "-Dsbt.log.noformat=true"
  SKIP_FLAKY_TRAVIS: "true"
defaults:
  run:
    shell: bash
on:
  push:
    branches: [ ccoco/WorkflowBuild ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [openjdk@1.8, openjdk@1.11]
        scala: [2.11.12, 2.12.8, 2.13.1]
        coverage: [false]
        include:
          - java: openjdk@1.8
            scala: 2.12.8
            coverage: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: ${{ matrix.java }}
      - name: cache/maven
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: cache/ivy2-cache
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-${{ github.repository }}-${{ github.ref }}-sbt-ivy-cache-
      - name: cache/ivy2-local
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/local/com.twitter
          key: ${{ runner.os }}-${{ github.repository }}-${{ github.ref }}-sbt-ivy-local-
      - name: cache/sbt
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-${{ matrix.java }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: test
        if: ${{ !matrix.coverage }}
        run: |
          ./sbt ++${{ matrix.scala }} clean test
      - name: test/with-coverage
        if: ${{ matrix.coverage }}
        run: |
          ./sbt ++${{ matrix.scala }} clean coverage test coverageReport
      - name: test/coverage-report/generate
        if: ${{ matrix.coverage }}
        run: |
          ./sbt ++${{ matrix.scala }} coverageAggregate
      - name: test/coverage-report/generate
        if: ${{ matrix.coverage }}
        run: |
          ./sbt ++${{ matrix.scala }} coverageAggregate
      - name: test/coverage-report/save-results
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ./**/target/scala-2.12/*-report/*.xml
  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: test/coverage-report/download-results
        uses: actions/download-artifact@v1
        with:
          name: coverage-report
          path: ${{ github.workspace }}/coverage-reports
      - name: test/coverage-report/upload
        if: ${{ matrix.coverage == 'true' && success() }}
        uses: codecov/codecov-action@v1
        with:
          file: ${{ github.workspace }}/coverage-reports
