name: Continuous Integration

on:
  push:
    branches: [ develop ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        java: [openjdk@1.8, openjdk@1.11]
        scala: [2.11.12, 2.12.8, 2.13.1]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: ${{ matrix.java }}
      - name: cache maven
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: cache sbt ivy cache
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}
      - name: cache sbt
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: unset SBT_OPTS # default $SBT_OPTS is irrelevant to sbt launcher
        shell: bash
        run: |
          unset SBT_OPTS
      - name: test with coverage
        shell: bash
        env:
          JAVA_OPTS: "-Dsbt.log.noformat=true"
        run: |
          ./sbt ++${{ matrix.scala }} clean coverage test coverageReport
      - name: generate aggregate coverage report
        shell: bash
        env:
          JAVA_OPTS: "-Dsbt.log.noformat=true"
        run: |
          ./sbt ++${{ matrix.scala }} coverageAggregate
      - name: upload coverage to codecov.io  
        uses: codecov/codecov-action@v1
